M48
; DRILL file {KiCad 7.0.10-7.0.10~ubuntu22.04.1} date Fri 16 Feb 2024 12:07:09 PM EST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-02-16T12:07:09-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10-7.0.10~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0827
%
G90
G05
T1
X4.35Y-2.95
X4.35Y-6.0
X6.15Y-6.0
X6.25Y-2.95
M30
